Repository retaildevcrews/loderunner, pull requests merged in 2021-09, with the labels that each got.

#31 Addressing some linter issues
  Ngsa.LodeRunner.csproj
  src/Program.cs
  src/events/ClientStatusEventArgs.cs
  src/events/ProcessingEventBus.cs
Labels: Bug

#32 Initial LoadRunner DAL refactor and registration Status in CosmosDB
  Ngsa.DataAccessLayer/CosmosConfig.cs
  Ngsa.DataAccessLayer/CosmosDBRepository.cs
  Ngsa.DataAccessLayer/CosmosDBSettings.cs
  Ngsa.DataAccessLayer/Extensions/StringExtensions.cs
  Ngsa.DataAccessLayer/Interfaces/IBaseEntityModel.cs
  Ngsa.DataAccessLayer/Interfaces/IBaseService.cs
  Ngsa.DataAccessLayer/Interfaces/IClientStatusService.cs
  Ngsa.DataAccessLayer/Interfaces/IConfig.cs
  Ngsa.DataAccessLayer/Interfaces/ICosmosDBRepository.cs
  Ngsa.DataAccessLayer/Interfaces/ICosmosDBSettings.cs
  Ngsa.DataAccessLayer/Interfaces/ILoadTestConfigService.cs
  Ngsa.DataAccessLayer/Interfaces/IModelValidator.cs
  Ngsa.DataAccessLayer/Interfaces/IRepository.cs
  Ngsa.DataAccessLayer/Interfaces/ISettingsValidator.cs
  Ngsa.DataAccessLayer/Model/BaseEntityModel.cs
  Ngsa.DataAccessLayer/Model/ClientStatus.cs
  Ngsa.DataAccessLayer/Model/ClientStatusType.cs
  Ngsa.DataAccessLayer/Model/EntityType.cs
  Ngsa.DataAccessLayer/Model/LoadClient.cs
  Ngsa.DataAccessLayer/Model/LoadResult.cs
  Ngsa.DataAccessLayer/Model/LoadTestConfig.cs
  Ngsa.DataAccessLayer/Model/TestRun.cs
  Ngsa.DataAccessLayer/Model/Validators/ClientStatusValidator.cs
  Ngsa.DataAccessLayer/Model/Validators/LoadClientValidator.cs
  Ngsa.DataAccessLayer/Ngsa.DataAccessLayer.csproj
  Ngsa.DataAccessLayer/Services/BaseService.cs
  Ngsa.DataAccessLayer/Services/ClientStatusService.cs
  Ngsa.DataAccessLayer/Services/LoadTestConfigService.cs
  Ngsa.DataAccessLayer/stylecop.json
  Ngsa.LodeRunner.csproj
  Ngsa.LodeRunner.sln
  secrets/CosmosCollection
  secrets/CosmosDatabase
  secrets/CosmosUrl
  src/DataAccessLayer/CosmosConfig.cs
  src/DataAccessLayer/dalMain.cs
  src/Interfaces/ILodeRunnerService.cs
  src/Program.cs
  src/Services/LodeRunnerService.cs
  src/ValidationTest/Main.cs
  src/ValidationTest/Model/config.cs
  src/ValidationTest/Validators/ParameterValidator.cs
  src/ValidationTest/Validators/ResponseValidator.cs
  src/core/CommandLine.cs
  src/core/Startup.cs
  src/core/SystemConstants.cs
  src/events/ClientStatusEventArgs.cs
  src/events/ProcessingEventBus.cs
Labels: Enhancement, size: L

#33 Disabled EnableNETAnalyzers and EnforceCodeStyleInBuild settings
  Ngsa.DataAccessLayer/Ngsa.DataAccessLayer.csproj
  Ngsa.LodeRunner.csproj
Labels: Bug, size: S

#34 Removed Windows native dll reference
  src/Program.cs
Labels: Bug

#35 Fixed logic to correctly intercept Ctrl+C and OnAppClose events
  src/Program.cs
  src/core/Startup.cs
Labels: Bug, Enhancement, size: S

#36 Clear dns cache
  src/ValidationTest/Main.cs
  src/ValidationTest/Model/config.cs
  src/core/CommandLine.cs
Labels: size: S

#38 Disable Push
  .github/workflows/ngsa.yaml
Labels: REFACTOR

#41 Merge Change feed capability
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
  src/LodeRunner.API.sln
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/src/Controllers/HealthzController.cs
  src/LodeRunner.API/src/Core/CommandLine.cs
  src/LodeRunner.API/src/Core/Config.cs
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/Data/Cache/CacheClients.cs
  src/LodeRunner.API/src/Data/Cache/CacheMain.cs
  src/LodeRunner.API/src/Data/Model/Client.cs
  src/LodeRunner.API/src/Data/Model/Enums.cs
  src/LodeRunner.API/src/DataAccessLayer/ChangeFeed/CustomObserver.cs
  src/LodeRunner.API/src/DataAccessLayer/ChangeFeed/Processor.cs
  src/LodeRunner.API/src/DataAccessLayer/Cosmos/CosmosConfig.cs
  src/LodeRunner.API/src/DataAccessLayer/Cosmos/dalClients.cs
  src/LodeRunner.API/src/DataAccessLayer/Cosmos/dalMain.cs
  src/LodeRunner.API/src/DataAccessLayer/Cosmos/idal.cs
  src/LodeRunner.API/src/DataAccessLayer/Model/ClientStatus.cs
  src/LodeRunner.API/src/DataAccessLayer/Model/LoadClient.cs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheck.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheckDetails.cs
  src/LodeRunner.API/src/Interfaces/ILRAPIChangeFeedService.cs
  src/LodeRunner.API/src/Program.cs
  src/LodeRunner.API/src/Services/LRAPIChangeFeedService.cs
  src/LodeRunner.API/src/Utilities/Parameters/ClientParameters.cs
  src/LodeRunner.API/src/Utilities/Parameters/ValidationError.cs
  src/LodeRunner.Core/Extensions/StringExtensions.cs
  src/LodeRunner.Core/Models/EntityType.cs
  src/LodeRunner.Data/ChangeFeed/LRObserver.cs
  src/LodeRunner.Data/ChangeFeed/LRObserverFactory.cs
  src/LodeRunner.Data/ChangeFeed/LRProcessor.cs
  src/LodeRunner.Data/ChangeFeed/ProcessChangesEventArgs.cs
  src/LodeRunner.Data/CosmosDBRepository.cs
  src/LodeRunner.Data/Interfaces/IBaseObserverFactory.cs
  src/LodeRunner.Data/Interfaces/IChangeFeedService.cs
  src/LodeRunner.Data/Interfaces/ICosmosDBRepository.cs
  src/LodeRunner.Data/Interfaces/IProcessor.cs
  src/LodeRunner.Data/LodeRunner.Data.csproj
  src/LodeRunner.Data/Services/ChangeFeedService.cs
  src/LodeRunner.Data/Services/ClientStatusService.cs
  src/LodeRunner/src/config.cs
Labels: REFACTOR, size: M, LodeRunner

#40 Update devcontainer lifecycle scripts to accommodate new folder structure
  .devcontainer/devcontainer.json
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
  Makefile
  src/.dockerignore
  src/LodeRunner.API/Dockerfile
Labels: Bug, TechnicalDebt

#43 Refactor Config and Secrets
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/src/Controllers/ClientsController.cs
  src/LodeRunner.API/src/Core/Config.cs
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/Data/Cache/CacheClients.cs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLoggerExtensions.cs
  src/LodeRunner.API/src/Interfaces/ILRAPICacheService.cs
  src/LodeRunner.API/src/Program.cs
  src/LodeRunner.API/src/Services/LRAPICacheService.cs
  src/LodeRunner.Core/Interfaces/ICommonConfig.cs
  src/LodeRunner.Core/Interfaces/ICosmosConfig.cs
  src/LodeRunner.Core/Interfaces/ILRConfig.cs
  src/LodeRunner.Core/Interfaces/ISecrets.cs
  src/LodeRunner.Core/LodeRunner.Core.csproj
  src/LodeRunner.Core/Models/LoadClient.cs
  src/LodeRunner.Core/Secrets.cs
  src/LodeRunner.Data/CosmosDBSettings.cs
  src/LodeRunner.Data/Interfaces/ICacheService.cs
  src/LodeRunner.sln
  src/LodeRunner/src/Program.cs
  src/LodeRunner/src/Services/LodeRunnerService.cs
  src/LodeRunner/src/config.cs
  src/LodeRunner/src/core/Secrets.cs
Labels: Enhancement, size: M, LoadGen, LodeRunner

#45 Rename CosmosDB
  .github/workflows/codeql-analysis.yml
  .github/workflows/ngsa-pr.yaml
  .github/workflows/ngsa.yaml
  docs/cosmos.md
  scripts/cosmos-create.sh
  src/LodeRunner.API/secrets/CosmosCollection
  src/LodeRunner.API/secrets/CosmosDatabase
  src/LodeRunner.API/secrets/CosmosTestDatabase
  src/LodeRunner.Data/README.md
  src/LodeRunner/secrets/CosmosCollection
  src/LodeRunner/secrets/CosmosDatabase
  src/LodeRunner/secrets/CosmosTestDatabase
Labels: Documentation, LoadGen, LodeRunner

#47 Added AutoGitops
  .github/workflows/ngsa.yaml
  autogitops/autogitops.json
  autogitops/ngsa-preprod.yaml
Labels: CI/CD
