Repository retaildevcrews/loderunner, pull requests merged in 2021-10, with the labels that each got.

#48 Added central cluster and replaced pod with deployment
  .github/workflows/ngsa.yaml
  autogitops/autogitops.json
  autogitops/ngsa-preprod.yaml
Labels: CI/CD

#46 Refactor Caching Layer
  src/LodeRunner.API/src/Controllers/ClientsController.cs
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/Core/SystemConstants.cs
  src/LodeRunner.API/src/Data/Cache/CacheClients.cs
  src/LodeRunner.API/src/Data/Cache/CacheMain.cs
  src/LodeRunner.API/src/Data/Cache/ICache.cs
  src/LodeRunner.API/src/Data/Cache/LRAPICache.cs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
  src/LodeRunner.API/src/Interfaces/ILRAPICache.cs
  src/LodeRunner.API/src/Program.cs
  src/LodeRunner.API/src/Services/LRAPICacheService.cs
  src/LodeRunner.Core/Cache/BaseAppCache.cs
  src/LodeRunner.Core/Cache/BaseMemoryCache.cs
  src/LodeRunner.Core/Interfaces/IAppCache.cs
  src/LodeRunner.Core/Interfaces/IModelValidator.cs
  src/LodeRunner.Core/LodeRunner.Core.csproj
  src/LodeRunner.Core/Models/ClientStatus.cs
  src/LodeRunner.Core/Models/Validators/BaseEntityValidator.cs
  src/LodeRunner.Core/Models/Validators/ClientStatusValidator.cs
  src/LodeRunner.Core/Models/Validators/LoadClientValidator.cs
  src/LodeRunner.Core/SystemConstants.cs
  src/LodeRunner.Data/LodeRunner.Data.csproj
  src/LodeRunner.Data/Secrets.cs
  src/LodeRunner.Data/Services/ClientStatusService.cs
  src/LodeRunner/src/Program.cs
Labels: DesignReview, size: L, LoadGen, LodeRunner

#49 Record Memory Cache Performance Metrics in a MD file.
  docs/MemoryCachePerfMetrics.md
Labels: SPIKE, LoadGen, LodeRunner

#50 Update to new autogitops format
  autogitops/autogitops.json
  autogitops/dev/loderunner.yaml
  autogitops/preprod/loderunner.yaml
Labels: CI-CD

#62 Autogitops workflow fix
  .github/workflows/loderunner-main-push.yaml
  .github/workflows/loderunner-only.yaml
Labels: Bug

#71 Update ClientStatus StatusDuration to LastStatusChange
  docs/DataDictionary.md
  src/LodeRunner.API/src/Data/Model/Client.cs
  src/LodeRunner.Core/Models/ClientStatus.cs
  src/LodeRunner.Core/Models/Validators/ClientStatusValidator.cs
  src/LodeRunner.Core/Version.cs
  src/LodeRunner.Data/Services/ClientStatusService.cs
  src/LodeRunner/src/Services/LodeRunnerService.cs
Labels: size: S, LoadGen, LodeRunner
