Repository retaildevcrews/loderunner, pull requests merged in 2021-12, with the labels that each got.

#85 Delete LoadTestConfig via LodeRunner.UI
  src/LodeRunner.UI/README.md
  src/LodeRunner.UI/package-lock.json
  src/LodeRunner.UI/package.json
  src/LodeRunner.UI/src/components/App/index.js
  src/LodeRunner.UI/src/components/App/styles.css
  src/LodeRunner.UI/src/components/Clients/index.js
  src/LodeRunner.UI/src/components/ConfigForm/index.js
  src/LodeRunner.UI/src/components/ConfigForm/styles.css
  src/LodeRunner.UI/src/components/Configs/index.js
  src/LodeRunner.UI/src/contexts/index.js
  src/LodeRunner.UI/src/services/configs.js
  src/LodeRunner.UI/src/services/configs.test.js
  src/LodeRunner.UI/src/services/utilities.js
Labels: Documentation, Enhancement, LoadGen, LRUI

#87 Add --mode Arg and Refactor CLI Args
  .github/workflows/loderunner-api.yaml
  .github/workflows/loderunner-only.yaml
  src/LodeRunner.API.Test/IntegrationTests/ComponentsFactory.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
  src/LodeRunner.API/src/Extensions/ModelExtensions.cs
  src/LodeRunner.Core/CommandLine/LRCommandLine.cs
  src/LodeRunner.Core/Interfaces/ILRConfig.cs
  src/LodeRunner.Core/LodeRunner.Core.xml
  src/LodeRunner.Core/Models/LoadClient.cs
  src/LodeRunner.Core/SystemConstants.cs
  src/LodeRunner.Test/UnitTests/CommandLineArgs.cs
  src/LodeRunner/Properties/launchSettings.json
  src/LodeRunner/README.md
  src/LodeRunner/src/Program.cs
  src/LodeRunner/src/Services/LodeRunnerService.cs
  src/LodeRunner/src/config.cs
Labels: size: M, LoadGen, LodeRunner

#88 Fixed delayStart bug and disabled two Integration Tests
  src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
  src/LodeRunner/src/Services/LodeRunnerService.cs
Labels: Bug, size: S, LodeRunner

#86 Update LodeRunner.UI dev experience instructions
  .gitignore
  Makefile
  README.md
  src/LodeRunner.API/.dockerignore
  src/LodeRunner.API/README.md
  src/LodeRunner.Data/README.md
  src/LodeRunner.UI/.dockerignore
  src/LodeRunner.UI/.eslintrc.json
  src/LodeRunner.UI/README.md
  src/LodeRunner.UI/babel.config.js
  src/LodeRunner.UI/jest.config.js
  src/LodeRunner.UI/package-lock.json
  src/LodeRunner.UI/package.json
  src/LodeRunner.UI/public/index.html
  src/LodeRunner.UI/src/components/App/styles.css
  src/LodeRunner.UI/src/components/Clients/styles.css
  src/LodeRunner.UI/src/index.css
  src/LodeRunner/.dockerignore
  src/LodeRunner/README.md
Labels: DevX, Documentation, LodeRunner, LRUI

#89 Fix bug LodeRunner.API 500 when only required values are POSTed
  src/LodeRunner.API/LodeRunnerApi.xml
  src/LodeRunner.API/src/Controllers/LoadTestConfigController.cs
  src/LodeRunner.API/src/Extensions/ModelExtensions.cs
  src/LodeRunner.Core/CommandLine/LRCommandLine.cs
  src/LodeRunner.Core/LodeRunner.Core.xml
  src/LodeRunner.Core/Models/LoadTestConfig.cs
  src/LodeRunner.Core/Models/LoadTestConfigPayload.cs
  src/LodeRunner.Test/UnitTests/CommandLineArgs.cs
Labels: Bug, size: S, LoadGen, LodeRunner

#90 LoadTestConfigs GET endpoint for LodeRunner.API
  src/LodeRunner.API/LodeRunnerApi.xml
  src/LodeRunner.API/src/Controllers/ClientsController.cs
  src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
  src/LodeRunner.API/src/Data/Cache/LRAPICache.cs
  src/LodeRunner.Core/LodeRunner.Core.xml
Labels: Enhancement, LoadGen

#92 Update LodeRunner.UI to display a message when no clients are available
  src/LodeRunner.UI/src/components/Clients/index.js
  src/LodeRunner.UI/src/components/Clients/styles.css
Labels: LRUI

#93 Add Load Test Config DELETE endpoint
  src/LodeRunner.API/LodeRunnerApi.xml
  src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
  src/LodeRunner.API/src/Core/SystemConstants.cs
  src/LodeRunner.Core/LodeRunner.Core.xml
  src/LodeRunner.Data/Interfaces/ILoadTestConfigService.cs
  src/LodeRunner.Data/Services/BaseService.cs
  src/LodeRunner.Data/Services/ClientStatusService.cs
  src/LodeRunner.Data/Services/LoadTestConfigService.cs
Labels: Enhancement

#95 Removed Required Attributes from DelayedStart
  src/LodeRunner.Core/Models/LoadTestConfig.cs
Labels: Enhancement

#98 Return undefined when for response body when API response is 204, No Content.
  src/LodeRunner.UI/package.json
  src/LodeRunner.UI/src/components/App/index.js
  src/LodeRunner.UI/src/components/Clients/index.js
  src/LodeRunner.UI/src/services/clients.js
  src/LodeRunner.UI/src/services/configs.js
  src/LodeRunner.UI/src/services/utilities.js
  src/LodeRunner.UI/src/services/utilities.test.js
Labels: LRUI

#96 Refactored liveness timer
  src/LodeRunner.Core/Interfaces/ILRConfig.cs
  src/LodeRunner.Core/LodeRunner.Core.xml
  src/LodeRunner/src/Services/LodeRunnerService.cs
  src/LodeRunner/src/config.cs
  src/LodeRunner/src/events/ProcessingEventBus.cs
Labels: REFACTOR

#100 Refactor LodeRunner.Events to LodeRunner.Core
  src/LodeRunner.Core/Events/ClientStatusEventArgs.cs
  src/LodeRunner.Core/Events/ProcessingEventBus.cs
  src/LodeRunner.Core/LodeRunner.Core.xml
  src/LodeRunner/LodeRunner.csproj
  src/LodeRunner/src/Services/LodeRunnerService.cs
Labels: Pri1, size: S, LoadGen, LodeRunner

#102 Removed mocked data and fixed endpoint name
  src/LodeRunner.UI/src/components/App/index.js
  src/LodeRunner.UI/src/services/configs.js
Labels: first-good-issue, LRUI

#101 Updated loderunner.yaml
  deploy/loderunner/local/2-loderunner.yaml
Labels: LoadGen, LodeRunner

#103 Test LodeRunner.UI update config and fixed endpoint name
  src/LodeRunner.UI/src/services/configs.js
Labels: good-first-issue, size: S, LoadGen, LRUI

#104 Updated UI with client mode required and optional values
  src/LodeRunner.UI/src/components/ClientDetails/index.js
  src/LodeRunner.UI/src/models/index.js
Labels: LoadGen, LodeRunner

#106 Updated LodeRunner.UI startup instructions
  Makefile
  README.md
  src/LodeRunner.UI/README.md
  src/LodeRunner/README.md
Labels: DevX, Documentation, LodeRunner, LRUI

#107 Update LodeRunner.UI with mode compatibility table details
  src/LodeRunner.UI/src/components/ConfigForm/index.js
  src/LodeRunner.UI/src/models/index.js
  src/LodeRunner.UI/src/services/configs.js
  src/LodeRunner.UI/src/services/configs.test.js
  src/LodeRunner.UI/src/utilities/types.js
  src/LodeRunner.UI/src/utilities/types.test.js
Labels: LoadGen, LRUI
