Repository retaildevcrews/loderunner, pull requests merged in 2022-12, with the labels that each got.

#319 Loderunner API MI Implementation
  README.md
  src/LodeRunner.API.Test/LodeRunner.API.Test.csproj
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/Properties/launchSettings.json
  src/LodeRunner.API/src/Core/Config.cs
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/Program.cs
  src/LodeRunner.Core/CommandLine/LRAPICommandLine.cs
  src/LodeRunner.Core/CommandLine/LRCommandLine.cs
  src/LodeRunner.Core/CosmosAuthType.cs
  src/LodeRunner.Core/Interfaces/ICosmosConfig.cs
  src/LodeRunner.Core/LodeRunner.Core.csproj
  src/LodeRunner.Data/CosmosDBRepository.cs
  src/LodeRunner.Data/CosmosDBSettings.cs
  src/LodeRunner.Data/Interfaces/IBaseService.cs
  src/LodeRunner.Data/Interfaces/ICosmosDBSettings.cs
  src/LodeRunner.Data/LodeRunner.Data.csproj
  src/LodeRunner.Data/README.md
  src/LodeRunner.Data/Secrets.cs
  src/LodeRunner.Test/LodeRunner.Test.csproj
  src/LodeRunner/LodeRunner.csproj
  src/LodeRunner/Properties/launchSettings.json
  src/LodeRunner/src/config.cs
Labels: size: M, LodeRunner

#325 Update LodeRunner Autogitops variables with values from new subscription
  autogitops/autogitops.json
Labels: CI-CD

#327 Parameterized keyvault names in loderunner-pod-identity.yaml autogitops template
  autogitops/dev/loderunner-pod-identity.yaml
  autogitops/preprod/loderunner-pod-identity.yaml
Labels: Bug
