Repository retaildevcrews/loderunner, pull requests merged in 2022-06, with the labels that each got.

#233 Upgrade LoadRunner Applications to .NET 6
  src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/LoadTestConfigs.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
  src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/TestRunExecution.cs
  src/LodeRunner.API.Test/LodeRunner.API.Test.csproj
  src/LodeRunner.API/Dockerfile
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/src/Handlers/ExceptionMiddleware/GlobalException.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheck.cs
  src/LodeRunner.Core/Extensions/CorrelationVectorExtensions.cs
  src/LodeRunner.Core/LodeRunner.Core.csproj
  src/LodeRunner.Core/Models/LoadClient.cs
  src/LodeRunner.Core/SystemConstants.cs
  src/LodeRunner.Core/Version.cs
  src/LodeRunner.Data/LodeRunner.Data.csproj
  src/LodeRunner.Test.sln
  src/LodeRunner.Test/LodeRunner.Test.csproj
  src/LodeRunner.Test/UnitTests/ConfigServerNamesTest.cs
  src/LodeRunner.Test/UnitTests/TestRunValidatorTest.cs
  src/LodeRunner/Dockerfile
  src/LodeRunner/LodeRunner.csproj
  src/LodeRunner/src/Services/LodeRunnerService.cs
  src/LodeRunner/src/Subscribers/ClientStatusUpdater.cs
  src/LodeRunner/src/ValidationTest/Main.cs
  src/LodeRunner/src/ValidationTest/Model/TimerRequestState.cs
  src/LodeRunner/src/core/CorrelationVectorExtensions.cs
Labels: TechnicalDebt, size: S, LoadGen, LodeRunner

#236 Add OpenTelemetry tracer to API headers
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
  src/LodeRunner.API/src/Program.cs
Labels: Enhancement, LodeRunner

#238 Update stylecop to beta release for LodeRunner Projects
  src/LodeRunner.API.Test/IntegrationTests/ApiPortPoolManager.cs
  src/LodeRunner.API.Test/IntegrationTests/ApiWebApplicationFactory.cs
  src/LodeRunner.API.Test/IntegrationTests/ComponentsFactory.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/LoadTestConfigs.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
  src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/ApiProcessContextCollection.cs
  src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/TestRunExecution.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/HttpClientExtension.cs
  src/LodeRunner.API.Test/LodeRunner.API.Test.csproj
  src/LodeRunner.API.Test/UnitTests/IntervalCheckerTest.cs
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/src/Controllers/HealthzController.cs
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/Extensions/ClientStatusServiceExtensions.cs
  src/LodeRunner.API/src/Extensions/TestRunsServiceExtensions.cs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
  src/LodeRunner.API/src/Handlers/ResultHandler.cs
  src/LodeRunner.API/src/Handlers/SwaggerExtension.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheck.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheckBuilderExtensions.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheckDetails.cs
  src/LodeRunner.API/src/HealthChecks/IetfCheck.cs
  src/LodeRunner.API/src/HealthChecks/IetfResponseWriter.cs
  src/LodeRunner.API/src/Utilities/Parameters/ParametersValidator.cs
  src/LodeRunner.Core/Automapper/BaseEntityAutoMapperHelper.cs
  src/LodeRunner.Core/Automapper/BasePayloadAutoMapperHelper.cs
  src/LodeRunner.Core/Automapper/BasePayloadToEntityAutoMapperHelper.cs
  src/LodeRunner.Core/CommandLine/LRAPICommandLine.cs
  src/LodeRunner.Core/CommandLine/LRCommandLine.cs
  src/LodeRunner.Core/CommandLine/Parsers.cs
  src/LodeRunner.Core/Extensions/LoadTestConfigExtensions.cs
  src/LodeRunner.Core/IntervalChecker.cs
  src/LodeRunner.Core/LodeRunner.Core.csproj
  src/LodeRunner.Core/Models/ClientStatusType.cs
  src/LodeRunner.Core/Models/EntityType.cs
  src/LodeRunner.Core/Models/LoadClient.cs
  src/LodeRunner.Core/Models/TestRun.cs
  src/LodeRunner.Core/Models/Validators/BaseEntityValidator.cs
  src/LodeRunner.Core/NgsaLogger/NgsaLogger.cs
  src/LodeRunner.Core/NgsaLogger/NgsaLoggerExtensions.cs
  src/LodeRunner.Core/NgsaLogger/NgsaLoggerProvider.cs
  src/LodeRunner.Data/CosmosDBRepository.cs
  src/LodeRunner.Data/LodeRunner.Data.csproj
  src/LodeRunner.Data/Secrets.cs
  src/LodeRunner.Test/Common/SecretsHelper.cs
  src/LodeRunner.Test/LodeRunner.Test.csproj
  src/LodeRunner.Test/UnitTests/ConfigServerNamesTest.cs
  src/LodeRunner.Test/UnitTests/TestRunValidatorTest.cs
  src/LodeRunner/LodeRunner.csproj
  src/LodeRunner/src/Extensions/ClientModeExtensions.cs
  src/LodeRunner/src/Program.cs
  src/LodeRunner/src/Services/LodeRunnerService.cs
  src/LodeRunner/src/ValidationTest/Main.cs
  src/LodeRunner/src/ValidationTest/ReadValidateJson.cs
  src/LodeRunner/src/ValidationTest/Validators/ParameterValidator.cs
  src/LodeRunner/src/ValidationTest/Validators/ResponseValidator.cs
Labels: TechnicalDebt, size: S, LoadGen, LodeRunner

#241 Remove edit feature from LR.UI for the client name in details.
  src/LodeRunner.UI/src/components/ClientDetails/index.js
Labels: LoadGen, LRUI

#240 Feature/cosmos emul enhancements
  .devcontainer/cosmos-emulator/Dockerfile
  .devcontainer/cosmos-emulator/gen-multi-domain-cert.bash
  .devcontainer/cosmos-emulator/nginx-http-template.conf
  .devcontainer/cosmos-emulator/pre-startup.bash
  .devcontainer/cosmos-emulator/setup-cosmos-emulator.sh
  .devcontainer/cosmos-emulator/start-cosmos-emulator.sh
  .devcontainer/devcontainer.json
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
  .devcontainer/post-start.sh
  Makefile
  README.md
  deploy/loderunner/local-cosmos/1-namespace.yaml
  deploy/loderunner/local-cosmos/2-loderunner.yaml
  deploy/loderunner/local-cosmos/3-loderunner-api.yaml
  deploy/loderunner/local-cosmos/4-loderunner-ui.yaml
  deploy/loderunner/local-cosmos/README.md
  deploy/loderunner/local-cosmos/saveenv.sh
  src/LodeRunner.Data/Secrets.cs
Labels: DevX, Enhancement, size: L, LoadGen

#245 Fix UI issue where modal can be closed by clicking in the modal and releasing outside the modal
  src/LodeRunner.UI/src/components/Modal/index.js
  src/LodeRunner.UI/src/components/Modal/styles.css
Labels: Bug, LRUI

#243 Open config detail by selecting config from list in LR.UI
  src/LodeRunner.UI/src/components/App/styles.css
  src/LodeRunner.UI/src/components/Configs/index.js
  src/LodeRunner.UI/src/services/utilities.js
Labels: Enhancement, LoadGen, LRUI

#249 Nudoyen/mlc updates
  .github/ISSUE_TEMPLATE/EngineeringFundChecklist.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/workflows/mdlinkcheck.yml
  docs/EngineeringPractices.md
  docs/SECURITY.md
  mlc_config.json
  src/LodeRunner.API/README.md
  src/LodeRunner.UI/README.md
  src/LodeRunner/README.md
Labels: CI/CD

#247 Bugfix: Cosmos Emulator's sleep disorder
  .devcontainer/cosmos-emulator/setup-cosmos-emulator.sh
  .devcontainer/cosmos-emulator/start-cosmos-emulator.sh
Labels: Bug

#244 Load Test Config UI updates
  src/LodeRunner.UI/src/components/ConfigForm/index.js
  src/LodeRunner.UI/src/components/ResultPage/index.js
  src/LodeRunner.UI/src/components/TestSubmission/index.js
Labels: LoadGen, LodeRunner

#251 Run MDLint on PRs only
  .github/workflows/markdownlint.yml
Labels: Bug, CI/CD

#252 Redesign LR.UI detailed test run result page
  src/LodeRunner.UI/src/components/Modal/index.js
  src/LodeRunner.UI/src/components/Modal/styles.css
  src/LodeRunner.UI/src/components/ResultPage/index.js
  src/LodeRunner.UI/src/components/ResultPage/styles.css
  src/LodeRunner.UI/src/components/ResultsOverviewPage/index.js
  src/LodeRunner.UI/src/components/TestSubmission/index.js
Labels: LoadGen, LRUI

#259 LodeRunner.UI - Fix Lint Rules Conflict
  src/LodeRunner.UI/package-lock.json
  src/LodeRunner.UI/package.json
Labels: Bug

#257 Show logs from detached container when it stops unexpectedly.
  .github/workflows/loderunner-api.yaml
  .github/workflows/loderunner-only.yaml
  .github/workflows/loderunner-ui.yaml
Labels: CI/CD

#260 Added exception logging to ExecuteNewTestRunAsync
  src/LodeRunner/src/Services/LodeRunnerService.cs
Labels: LodeRunner

#262 Move Cosmos Emulator setup to onCreate for Prebuild
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
Labels: size: S, LoadGen

#263 Updated secrets in workflow, turned off card creation in scheduled link check
  .github/workflows/loderunner-main-pr.yaml
  .github/workflows/loderunner-main-push.yaml
  .github/workflows/scheduled_mdlinkcheck.yaml
  docs/cosmos.md
  src/LodeRunner.API.Test/IntegrationTests/Controllers/LoadTestConfigs.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
Labels: CI/CD

#264 Delete userstory.md
  .github/ISSUE_TEMPLATE/userstory.md
Labels: Bug
