Repository retaildevcrews/loderunner, pull requests merged in 2022-07, with the labels that each got.

#265 Ensure all paths for run-loop and run-once use UpdateTestRun event
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
  src/LodeRunner/src/ValidationTest/Main.cs
Labels: Bug, size: S, LoadGen, LodeRunner

#266 Add Codespace .NET dev environment for LodeRunner repo
  .devcontainer/devcontainer.json
  .devcontainer/on-create.sh
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  omnisharp.json
Labels: DevX

#267 Added a workflow with GitHub action to check for CRLF line endings
  .github/workflows/crlf-check.yaml
  src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/HttpClientExtension.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/LoadClientExtension.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/LoadTestConfigExtension.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/TestRunPayloadExtension.cs
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/src/Controllers/TestRunsController.cs
  src/LodeRunner.API/src/Core/SystemConstants.cs
  src/LodeRunner.API/src/Core/TimeSpanConverter.cs
  src/LodeRunner.API/src/Data/Model/Client.cs
  src/LodeRunner.API/src/Extensions/AutoMapperProfileExtensions.cs
  src/LodeRunner.API/src/Extensions/ErrorResult.cs
  src/LodeRunner.API/src/Extensions/ModelExtensions.cs
  src/LodeRunner.API/src/Extensions/TestRunsServiceExtensions.cs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLoggerExtensions.cs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLoggerOptions.cs
  src/LodeRunner.API/src/Handlers/ResultHandler.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheckBuilderExtensions.cs
  src/LodeRunner.API/src/HealthChecks/HealthzCheck.cs
  src/LodeRunner.API/src/HealthChecks/IetfCheck.cs
  src/LodeRunner.API/src/Program.cs
  src/LodeRunner.API/src/Utilities/Parameters/ParametersValidator.cs
  src/LodeRunner.API/stylecop.json
  src/LodeRunner.Core/Interfaces/IModelValidator.cs
  src/LodeRunner.Core/Models/BaseEntityModel.cs
  src/LodeRunner.Core/Models/BasePayload.cs
  src/LodeRunner.Core/Models/ClientStatus.cs
  src/LodeRunner.Core/Models/LoadClient.cs
  src/LodeRunner.Core/Models/TestRun.cs
  src/LodeRunner.Core/Models/TestRunPayload.cs
  src/LodeRunner.Core/Models/Validators/BaseEntityValidator.cs
  src/LodeRunner.Core/Models/Validators/LoadResultValidator.cs
  src/LodeRunner.Core/SchemaFilters/LoadResultSchemaFilter.cs
  src/LodeRunner.Data/Services/LoadTestConfigService.cs
Labels: CI/CD, Enhancement, DevOps

#275 Added Grype vulnerability scanner
  .github/workflows/loderunner-api.yaml
  .github/workflows/loderunner-only.yaml
  .github/workflows/loderunner-ui.yaml
Labels: size: S, CI-CD, DevOps

#270 added checkov action, skip statements
  .devcontainer/Dockerfile
  .devcontainer/cosmos-emulator/Dockerfile
  .github/workflows/checkov-docker.yml
  src/LodeRunner.API/Dockerfile
  src/LodeRunner.UI/Dockerfile
  src/LodeRunner/Dockerfile
Labels: CI/CD, Enhancement, DevOps

#274 Refactor Clients Integration test and separate a method to a different file
  src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/TestResponses.cs
Labels: LoadGen, LodeRunner

#279 Markdown Link Check Action bug fix
  mlc_config.json
Labels: Bug, DevOps

#278 Set Port Visibility
  .devcontainer/devcontainer.json
  README.md
Labels: LoadGen

#271 updated instructions to run integration tests in CodeSpaces
  README.md
Labels: Documentation, LoadGen, LodeRunner

#282 Removed CRLF configuration from editorconfig
  src/LodeRunner.API/src/.editorconfig
  src/LodeRunner/src/.editorconfig
Labels: Bug, DevX, LodeRunner

#283 Add Checkov VS code Task to Codespaces and populate a summary section.
  .gitignore
  .vscode/tasks.json
  README.md
Labels: Bug, size: S, LoadGen, LodeRunner, DevOps

#287 updated documentation for running unit tests to get key for resource …
  README.md
Labels: Documentation, LodeRunner

#289 BugFix - Remove ParentSpanID from LodeRunner
  src/LodeRunner/src/ValidationTest/Main.cs
  src/LodeRunner/src/ValidationTest/Model/PerfLog.cs
Labels: Bug, Observability, size: S
