Repository retaildevcrews/loderunner, pull requests merged in 2022-01, with the labels that each got.

#108 LodeRunner.UI feature to post a test run.
  src/LodeRunner.UI/src/components/App/index.js
  src/LodeRunner.UI/src/components/App/styles.css
  src/LodeRunner.UI/src/components/CheckMarkIcon/index.js
  src/LodeRunner.UI/src/components/ClientDetails/index.js
  src/LodeRunner.UI/src/components/ClientDetails/styles.css
  src/LodeRunner.UI/src/components/Clients/index.js
  src/LodeRunner.UI/src/components/Clients/styles.css
  src/LodeRunner.UI/src/components/ConfigForm/ArrayOfStringInput/index.js
  src/LodeRunner.UI/src/components/ConfigForm/BooleanInput/index.js
  src/LodeRunner.UI/src/components/ConfigForm/IntegerInput/index.js
  src/LodeRunner.UI/src/components/ConfigForm/StringInput/index.js
  src/LodeRunner.UI/src/components/ConfigForm/index.js
  src/LodeRunner.UI/src/components/Configs/index.js
  src/LodeRunner.UI/src/components/Configs/styles.css
  src/LodeRunner.UI/src/components/Modal/index.js
  src/LodeRunner.UI/src/components/PencilIcon/index.js
  src/LodeRunner.UI/src/components/PlayIcon/index.js
  src/LodeRunner.UI/src/components/TestSubmission/index.js
  src/LodeRunner.UI/src/components/TestSubmission/styles.css
  src/LodeRunner.UI/src/components/TrashIcon/index.js
  src/LodeRunner.UI/src/models/index.js
  src/LodeRunner.UI/src/services/configs.js
  src/LodeRunner.UI/src/services/configs.test.js
  src/LodeRunner.UI/src/services/testRun.js
  src/LodeRunner.UI/src/utilities/constants.js
Labels: Enhancement, LoadGen, LRUI

#109 Add navigation/routing to LodeRunner.UI
  src/LodeRunner.UI/package-lock.json
  src/LodeRunner.UI/package.json
  src/LodeRunner.UI/src/components/App/index.js
  src/LodeRunner.UI/src/components/App/routes.js
  src/LodeRunner.UI/src/components/App/styles.css
  src/LodeRunner.UI/src/components/ClientDetails/index.js
  src/LodeRunner.UI/src/components/Clients/index.js
  src/LodeRunner.UI/src/components/ConfigForm/index.js
  src/LodeRunner.UI/src/components/Configs/index.js
  src/LodeRunner.UI/src/components/Configs/styles.css
  src/LodeRunner.UI/src/components/ContentPage/index.js
  src/LodeRunner.UI/src/components/Modal/index.js
  src/LodeRunner.UI/src/components/NotFoundPage/index.js
  src/LodeRunner.UI/src/components/ResultPage/index.js
  src/LodeRunner.UI/src/components/ResultsOverviewPage/index.js
  src/LodeRunner.UI/src/components/ResultsOverviewPage/styles.css
  src/LodeRunner.UI/src/components/TestPage/index.js
  src/LodeRunner.UI/src/components/TestPage/styles.css
  src/LodeRunner.UI/src/components/TestSubmission/index.js
  src/LodeRunner.UI/src/contexts/app.js
  src/LodeRunner.UI/src/contexts/display.js
  src/LodeRunner.UI/src/contexts/index.js
  src/LodeRunner.UI/src/contexts/testPage.js
  src/LodeRunner.UI/src/index.css
  src/LodeRunner.UI/src/index.js
Labels: Enhancement, LoadGen, LRUI

#111 LodeRunner.UI test run overview and test run result pages
  src/LodeRunner.UI/src/components/App/index.js
  src/LodeRunner.UI/src/components/App/styles.css
  src/LodeRunner.UI/src/components/ClientDetails/index.js
  src/LodeRunner.UI/src/components/Configs/index.js
  src/LodeRunner.UI/src/components/Configs/styles.css
  src/LodeRunner.UI/src/components/Modal/index.js
  src/LodeRunner.UI/src/components/RefreshIcon/index.js
  src/LodeRunner.UI/src/components/ResultPage/index.js
  src/LodeRunner.UI/src/components/ResultPage/styles.css
  src/LodeRunner.UI/src/components/ResultsOverviewPage/index.js
  src/LodeRunner.UI/src/components/ResultsOverviewPage/styles.css
  src/LodeRunner.UI/src/components/TestPage/index.js
  src/LodeRunner.UI/src/components/TestSubmission/index.js
  src/LodeRunner.UI/src/components/TestSubmission/styles.css
  src/LodeRunner.UI/src/index.css
  src/LodeRunner.UI/src/models/index.js
  src/LodeRunner.UI/src/services/results.js
Labels: Enhancement, LoadGen, LRUI

#112 Replace Cache and Change feed with Direct Calls
  docs/cosmos.md
  docs/diagrams/source/LodeRunner.API.puml
  scripts/cosmos-create.sh
  src/LodeRunner.API.Test/IntegrationTests/ComponentsFactory.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
  src/LodeRunner.API.Test/IntegrationTests/HttpClientExtension.cs
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/LodeRunnerApi.xml
  src/LodeRunner.API/src/Controllers/ClientsController.cs
  src/LodeRunner.API/src/Core/Config.cs
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/Data/Cache/LRAPICache.cs
  src/LodeRunner.API/src/Extensions/ClientStatusServiceExtensions.cs
  src/LodeRunner.API/src/Handlers/ResultHandler.cs
  src/LodeRunner.API/src/Interfaces/ILRAPICache.cs
  src/LodeRunner.API/src/Interfaces/ILRAPIChangeFeedService.cs
  src/LodeRunner.API/src/Interfaces/ISystemComponentsService.cs
  src/LodeRunner.API/src/Program.cs
  src/LodeRunner.API/src/Services/LRAPIChangeFeedService.cs
  src/LodeRunner.API/src/Services/SystemComponentsService.cs
  src/LodeRunner.Core/Cache/BaseAppCache.cs
  src/LodeRunner.Core/Cache/BaseMemoryCache.cs
  src/LodeRunner.Core/Interfaces/IAppCache.cs
  src/LodeRunner.Core/LodeRunner.Core.csproj
  src/LodeRunner.Core/LodeRunner.Core.xml
  src/LodeRunner.Data/ChangeFeed/LRObserver.cs
  src/LodeRunner.Data/ChangeFeed/LRObserverFactory.cs
  src/LodeRunner.Data/ChangeFeed/LRProcessor.cs
  src/LodeRunner.Data/ChangeFeed/ProcessChangesEventArgs.cs
  src/LodeRunner.Data/CosmosDBRepository.cs
  src/LodeRunner.Data/Interfaces/IBaseObserverFactory.cs
  src/LodeRunner.Data/Interfaces/IChangeFeedService.cs
  src/LodeRunner.Data/Interfaces/ICosmosDBRepository.cs
  src/LodeRunner.Data/Interfaces/IProcessor.cs
  src/LodeRunner.Data/LodeRunner.Data.csproj
  src/LodeRunner.Data/README.md
  src/LodeRunner.Data/Services/ChangeFeedService.cs
Labels: REFACTOR, size: M, LoadGen, LodeRunner

#113 Updating links to repo source code readmes
  README.md
Labels: Bug, Documentation, size: S, LodeRunner

#115 Updated StatusUpdate calls
  src/LodeRunner/src/Services/LodeRunnerService.cs
Labels: Bug, LoadGen, LodeRunner

#114 Log LoadClientId
  .gitignore
  src/LodeRunner.API/LodeRunnerApi.xml
  src/LodeRunner.Core/Interfaces/ILRConfig.cs
  src/LodeRunner.Core/LodeRunner.Core.xml
  src/LodeRunner.Core/Models/LoadClient.cs
  src/LodeRunner/src/ValidationTest/Main.cs
  src/LodeRunner/src/ValidationTest/Model/PerfLog.cs
  src/LodeRunner/src/config.cs
Labels: Enhancement

#116 Updated clientStatusId error message
  src/LodeRunner.API/src/Core/SystemConstants.cs
Labels: Bug, LoadGen

#118 Reviewed and updated packages
  src/LodeRunner.API/LodeRunner.API.csproj
  src/LodeRunner.API/README.md
  src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
  src/LodeRunner.API/src/Core/NgsaLog.cs
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheck.cs
  src/LodeRunner.Core/LodeRunner.Core.csproj
  src/LodeRunner.Data/LodeRunner.Data.csproj
  src/LodeRunner/LodeRunner.csproj
  src/LodeRunner/src/ValidationTest/Main.cs
Labels: TechnicalDebt, LoadGen

#120 Run Integration Test Cases In CI/CD
  .github/workflows/loderunner-api.yaml
Labels: CI/CD

#123 Added md linter and link checker
  .github/CHANGELOG.md
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/EngineeringPractices.md
  .github/ISSUE_TEMPLATE/EngineeringFundChecklist.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/found-dead-links.md
  .github/LICENSE
  .github/SECURITY.md
  .github/SUPPORT.md
  .github/WorkingAgreement.md
  .github/workflows/markdownlint.yml
  .github/workflows/mdlinkcheck.yml
  .github/workflows/scheduled_mdlinkcheck.yaml
  .markdown.style.rb
  .mdlrc
  docs/DataDictionary.md
  docs/EngineeringPractices.md
  docs/HttpErrorResponses.md
  docs/MemoryCachePerfMetrics.md
  docs/SUPPORT.md
  docs/WorkingAgreement.md
  docs/cosmos.md
  docs/observability.md
  mlc_config.json
  src/LodeRunner.API/README.md
  src/LodeRunner/README.md
Labels: Enhancement, LodeRunner

#127 Changed autogitops workflow to use docker
  .github/workflows/loderunner-only.yaml
Labels: size: S

#128 Added east and westus2 targets to loderunner
  autogitops/autogitops.json
Labels: size: S

#130 updated load client name
  src/LodeRunner.Core/Models/LoadClient.cs
Labels: LoadGen, LodeRunner

#122 Log error messages from creating and testing Cosmos client
  src/LodeRunner.Core/Models/ExceptionLogEntry.cs
  src/LodeRunner.Data/CosmosDBRepository.cs
Labels: size: S

#126 Remove mock data for TestRuns in LodeRunner.UI
  README.md
  src/LodeRunner.API.Test/secrets/CosmosUrl
  src/LodeRunner.API/secrets/CosmosUrl
  src/LodeRunner.UI/src/components/ClientDetails/index.js
  src/LodeRunner.UI/src/components/Clients/index.js
  src/LodeRunner.UI/src/components/Clients/styles.css
  src/LodeRunner.UI/src/components/ResultPage/index.js
  src/LodeRunner.UI/src/components/ResultPage/styles.css
  src/LodeRunner.UI/src/components/ResultsOverviewPage/index.js
  src/LodeRunner.UI/src/components/ResultsOverviewPage/styles.css
  src/LodeRunner.UI/src/components/TestPage/index.js
  src/LodeRunner.UI/src/components/TestSubmission/index.js
  src/LodeRunner.UI/src/models/index.js
  src/LodeRunner.UI/src/utilities/datetime.js
  src/LodeRunner.UI/src/utilities/datetime.test.js
  src/LodeRunner/secrets/CosmosUrl
Labels: Documentation, TechnicalDebt, size: S, LoadGen, LRUI

#129 Add Integration Tests for LoadTestConfig controller
  src/LodeRunner.API.Test/IntegrationTests/Controllers/LoadTestConfigs.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/HttpClientExtension.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/LoadTestConfigExtension.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/TestRunPayloadExtension.cs
  src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
  src/LodeRunner.Core/Automapper/AutoMapperExtension.cs
  src/LodeRunner.Core/Automapper/BaseEntityAutoMapperHelper.cs
  src/LodeRunner.Core/Automapper/BasePayloadAutoMapperHelper.cs
  src/LodeRunner.Core/LodeRunner.Core.csproj
Labels: size: M, LoadGen, LodeRunner

#135 Removed old asb dev cluster in autogitops config
  autogitops/autogitops.json
Labels: size: S

#133 Implement TestRun running state check before deletion
  docs/DataDictionary.md
  src/LodeRunner.API.Test/IntegrationTests/ApiWebApplicationFactory.cs
  src/LodeRunner.API.Test/IntegrationTests/ComponentsFactory.cs
  src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
  src/LodeRunner.API/src/Controllers/TestRunsController.cs
  src/LodeRunner.API/src/Core/SystemConstants.cs
  src/LodeRunner.Core/Models/TestRun.cs
  src/LodeRunner.Core/Models/TestRunPayload.cs
  src/LodeRunner.Core/SchemaFilters/TestRunSchemaFilter.cs
Labels: Enhancement, LoadGen
