Repository retaildevcrews/loderunner, pull requests merged in 2022-03, with the labels that each got.

#168 Fix Loderunner in command mode fails when multiple servers are specified
  src/LodeRunner.API.Test/IntegrationTests/ApiPortPoolManager.cs
  src/LodeRunner.API.Test/IntegrationTests/ApiWebApplicationFactory.cs
  src/LodeRunner.API.Test/IntegrationTests/Common.cs
  src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/ApiProcessContextCollection.cs
  src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/TestRunExecution.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/HttpClientExtension.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/TestRunPayloadExtension.cs
  src/LodeRunner.API/src/HealthChecks/CosmosHealthCheck.cs
  src/LodeRunner.Test/UnitTests/TestRunValidatorTest.cs
  src/LodeRunner/src/ValidationTest/Main.cs
Labels: Bug, Testing:Load, size: M, LodeRunner

#171 Battle Station Part 1: LR.API GitOps Setup
  autogitops/autogitops.json
  autogitops/dev/loderunner-api.yaml
  autogitops/dev/loderunner-pod-identity.yaml
  autogitops/dev/loderunner.yaml
  autogitops/preprod/loderunner.yaml
Labels: CI/CD

#176 Github action to build image/package for LR UI
  .github/workflows/loderunner-ui.yaml
Labels: CI/CD, LoadGen, LRUI, CI-CD, DevOps

#173 Added CreateDeleteResponse to ResultHandler, Refactored GET, POST and DELETE response methods
  src/LodeRunner.API/src/Controllers/ClientsController.cs
  src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
  src/LodeRunner.API/src/Controllers/TestRunsController.cs
  src/LodeRunner.API/src/Core/SystemConstants.cs
  src/LodeRunner.API/src/Handlers/ResultHandler.cs
Labels: REFACTOR

#177 Update lR UI github action build target image and removed version request
  .github/workflows/loderunner-ui.yaml
Labels: CI/CD, LoadGen, CI-CD, DevOps

#178 Populate verison in LR UI for github action main push
  .github/workflows/loderunner-ui.yaml
  src/LodeRunner.UI/package.json
Labels: CI/CD, LoadGen, CI-CD, DevOps

#179 Bug fix: LodeRunner needs to poll TestRuns by LoadClient.Id
  src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/TestRunExecution.cs
  src/LodeRunner.API.Test/IntegrationTests/Extensions/TestRunPayloadExtension.cs
  src/LodeRunner.API/src/Core/Startup.cs
  src/LodeRunner.API/src/Core/SystemConstants.cs
  src/LodeRunner.Core/SystemConstants.cs
  src/LodeRunner.Data/Interfaces/ITestRunService.cs
  src/LodeRunner.Data/Services/TestRunService.cs
  src/LodeRunner/src/Services/LodeRunnerService.cs
  src/LodeRunner/src/ValidationTest/Main.cs
Labels: Bug, size: S, LoadGen, LodeRunner

#183 Revert "Populate version in LR UI for github action main push (#178)"
  .github/workflows/loderunner-ui.yaml
  src/LodeRunner.UI/package.json
Labels: CI/CD, LoadGen, CI-CD, DevOps

#184 Added start-nginx.sh for envsubst
  .github/workflows/loderunner-ui.yaml
  Makefile
  src/LodeRunner.UI/.env.production
  src/LodeRunner.UI/Dockerfile
  src/LodeRunner.UI/start-nginx.sh
Labels: LoadGen, LRUI

#185 Update LR.API script to replace LRAPI_DNS variable
  src/LodeRunner.UI/start-nginx.sh
Labels: CI/CD, LoadGen, LRUI, CI-CD, DevOps

#186 Update workflow to include sh files for LR.UI image build
  .github/workflows/loderunner-main-push.yaml
Labels: CI/CD, LoadGen, LRUI, CI-CD, DevOps

#187 Allow LR.UI routing w/ Virtual Service
  .github/workflows/loderunner-main-push.yaml
  src/LodeRunner.UI/Dockerfile
  src/LodeRunner.UI/nginx.conf
Labels: CI/CD, LoadGen, LRUI, CI-CD, DevOps

#188 Add LR.UI deployment files for dev.
  autogitops/autogitops.json
  autogitops/dev/loderunner-ui.yaml
Labels: CI/CD, LoadGen, LRUI, CI-CD, DevOps

#189 Update LR.UI for local dev cluster
  README.md
  deploy/loderunner/local/4-loderunner-ui.yaml
  src/LodeRunner.UI/package-lock.json
Labels: CI/CD, Documentation, LoadGen, LRUI, CI-CD, DevOps

#182 Refactor NgsaLoggerExtensions and Ngsalogger to fix race condition
  src/LodeRunner.API.Test/IntegrationTests/ComponentsFactory.cs
  src/LodeRunner.API/src/Core/Config.cs
  src/LodeRunner.API/src/Program.cs
  src/LodeRunner.Core/Extensions/LoggingBuilderExtensions.cs
  src/LodeRunner.Core/Interfaces/ILogValues.cs
  src/LodeRunner.Core/NgsaLogger/NgsaLogger.cs
  src/LodeRunner.Core/NgsaLogger/NgsaLoggerExtensions.cs
  src/LodeRunner.Core/NgsaLogger/NgsaLoggerProvider.cs
  src/LodeRunner/src/Extensions/NgsaLoggerExtensions.cs
  src/LodeRunner/src/Program.cs
  src/LodeRunner/src/Services/LodeRunnerService.cs
  src/LodeRunner/src/Subscribers/ClientStatusUpdater.cs
  src/LodeRunner/src/ValidationTest/Main.cs
  src/LodeRunner/src/ValidationTest/Model/TimerRequestState.cs
  src/LodeRunner/src/ValidationTest/ReadValidateJson.cs
  src/LodeRunner/src/config.cs
  src/LodeRunner/src/core/Startup.cs
Labels: Bug, DesignReview, LoadGen, LodeRunner

#191 CORS BugFix - Enable CORS in Local Development
  src/LodeRunner.API/src/Core/Startup.cs
Labels: Bug

#190 Added Request Payload to Request Logs
  src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
Labels: Bug, LodeRunner

#194 Add autogitops pull and gitops deploy to LR API and UI. Tag and push LR to ghcr.
  .github/workflows/loderunner-api.yaml
  .github/workflows/loderunner-main-push.yaml
  .github/workflows/loderunner-only.yaml
  .github/workflows/loderunner-ui.yaml
Labels: CI/CD, LoadGen, LodeRunner, CI-CD, DevOps

#196 Fix loderunner autogitops workflow
  .github/workflows/loderunner-api.yaml
  .github/workflows/loderunner-main-push.yaml
  .github/workflows/loderunner-only.yaml
  .github/workflows/loderunner-ui.yaml
Labels: Bug, size: S, LodeRunner, CI-CD

#197 Template to deploy LodeRunner in client mode to dev cluster
  autogitops/autogitops.json
  autogitops/dev/loderunner-clientmode.yaml
  autogitops/dev/loderunner-commandmode.yaml
  autogitops/dev/loderunner-pod-identity.yaml
Labels: CI/CD, LodeRunner, CI-CD, DevOps

#199 Fixed image reference for loderunner
  autogitops/preprod/loderunner.yaml
Labels: size: S

#206 Refactor Config Form in LR.UI
  src/LodeRunner.UI/src/components/ConfigForm/ArrayOfStringInput/index.js
  src/LodeRunner.UI/src/components/ConfigPage/index.js
  src/LodeRunner.UI/src/components/CreateConfig/index.js
  src/LodeRunner.UI/src/components/TestSubmission/index.js
Labels: LoadGen, LRUI

#205 Fixed bug : Unable to Update LoadTestConfig
  src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
  src/LodeRunner.API/src/Controllers/TestRunsController.cs
  src/LodeRunner.API/src/Extensions/AutoMapperProfileExtensions.cs
  src/LodeRunner.API/src/Handlers/ResultHandler.cs
  src/LodeRunner.Core/Automapper/AutoMapperExtension.cs
  src/LodeRunner.Core/Automapper/BasePayloadToEntityAutoMapperHelper.cs
Labels: Bug, size: S, LoadGen, LodeRunner

#207 Refactor ResultHandler.CreatePutResponse
  src/LodeRunner.API/src/Handlers/ResultHandler.cs
Labels: REFACTOR, size: S, LoadGen, LodeRunner

#209 Updated docs and launchsettings.json to reflect latest dev cluster urls
  src/LodeRunner/Properties/launchSettings.json
  src/LodeRunner/README.md
Labels: good-first-issue, size: S, LoadGen, LodeRunner

#208 Remove 'delayStart' attribute from LoadTestConfig payload sample
  src/LodeRunner.Core/SchemaFilters/LoadTestConfigPayloadSchemaFilter.cs
  src/LodeRunner.Core/SchemaFilters/LoadTestConfigSchemaFilter.cs
  src/LodeRunner.Core/SchemaFilters/TestRunPayloadSchemaFilter.cs
  src/LodeRunner.Core/SchemaFilters/TestRunSchemaFilter.cs
Labels: Bug, size: S, LoadGen, LodeRunner

#211 Update LodeRunner --help message default values
  docs/DataDictionary.md
  src/LodeRunner.Core/CommandLine/Parsers.cs
  src/LodeRunner/README.md
Labels: size: S, LoadGen, LodeRunner

#210 Document full test run steps with dashboard view
  README.md
  mlc_config.json
Labels: Documentation, LoadGen

#215 Add LoadTestConfig Validation for TestRun POST and PUT
  src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
  src/LodeRunner.API/src/Controllers/TestRunsController.cs
Labels: Enhancement, size: S, LoadGen, LodeRunner

#218 Update Prometheus TODO in observability docs
  README.md
Labels: Documentation
